"""Investo shared data models (pydantic v2).

Foundation library — every other unit imports from here. The names
listed in :data:`__all__` constitute this package's stable public API;
anything else (e.g. the ``_validators`` helpers) is internal and must
not be relied on by sibling units.

Reference: aidlc-docs/inception/application-design/component-methods.md
"""

from investo.models.briefing import (
    TELEGRAM_MESSAGE_LIMIT,
    Briefing,
    BriefingNotification,
)
from investo.models.carryover import (
    BriefingCarryover,
    CarryoverEventType,
    CarryoverItem,
    CarryoverStatus,
    status_label_kr,
)
from investo.models.core_fact import (
    CORE_FACT_KEYWORDS,
    CORE_FACT_METADATA_PREFIX,
    CORE_FACT_TOLERANCE,
    CoreFact,
    core_fact_metadata_key,
    is_core_fact,
)
from investo.models.coverage import (
    SourceCollectionReport,
    SourceOutcome,
    SourceStatus,
    SourceTier,
    sanitize_source_error_message,
)
from investo.models.facts import (
    FactId,
    FactSnapshot,
    FactSourceTier,
    FactStatus,
    VerifiedFactBundle,
)
from investo.models.items import Category, NormalizedItem
from investo.models.macro import (
    MacroMetadataIssue,
    MacroMetadataIssueCode,
    MacroMetadataView,
    macro_metadata_view,
)
from investo.models.macro_lifecycle import MacroLifecycleEvent, MacroLifecycleStatus
from investo.models.market_anchor import (
    DEFAULT_HISTORY_WINDOW_DAYS,
    AnchorLabel,
    MarketAnchor,
    OHLCRow,
    anchor_label,
)
from investo.models.public_notification import PublicNotificationSummary
from investo.models.quality_history import QualityHistoryRow
from investo.models.results import (
    FailureContext,
    FailureStage,
    PipelineResult,
    PipelineStatus,
    SendResult,
)
from investo.models.sector import (
    ALL_SECTOR_TICKERS,
    BENCHMARK_TICKER,
    FIXED_SECTOR_UNIVERSE,
    METRIC_QUANTUM,
    PRIMARY_REGIME_POLICY,
    RANK_HORIZONS,
    REGIME_BANDS_BPS,
    SECTOR_SOURCE_ID,
    SECTOR_TICKERS,
    SECTOR_UNIVERSE_VERSION,
    AxisState,
    CoverageSummary,
    DiagnosticIssueCode,
    MetricMissingReason,
    MetricValue,
    NavPoint,
    NavSeries,
    ParsedWorkbookSet,
    PrivateArtifactSet,
    PrivateDiagnostic,
    PrivateWorkbookManifest,
    RankHorizon,
    RegimePolicy,
    RegimeResult,
    RelativeRank,
    SectorCoverageStatus,
    SectorDashboardSnapshot,
    SectorMetricName,
    SectorMetrics,
    SectorRecord,
    SectorRegime,
    SectorSeriesBundle,
    SectorTicker,
    SectorUniverse,
    WorkbookFailure,
    WorkbookIssueCode,
)
from investo.models.segments import (
    CATEGORY_LABELS,
    COVERAGE_REASON_LABELS,
    COVERAGE_STATUS_LABELS,
    CRYPTO,
    DOMESTIC_EQUITY,
    SEGMENT_LABELS,
    SEGMENT_MARKET_TZ,
    SEGMENT_MARKET_TZ_LABEL,
    SEVERITY_READER_EXPLANATIONS,
    US_EQUITY,
    CoverageReasonCode,
    CoverageStatus,
    MarketSegment,
    SegmentCoverage,
)
from investo.models.time_state import TimeState
from investo.models.watchlist import (
    DEFAULT_BUNDLE_BADGE_LABEL,
    CoverageStatusInput,
    ImpactGroup,
    PublicWatchlistGroup,
    RejectedCandidate,
    RejectReason,
    WatchlistChannel,
    WatchlistImpact,
    WatchlistImpactCenter,
    WatchlistImpactStatus,
    WatchlistMatch,
    WatchlistTermKind,
    public_watchlist_match_group,
    public_watchlist_match_label,
    public_watchlist_match_summary,
)

__all__ = [
    "ALL_SECTOR_TICKERS",
    "BENCHMARK_TICKER",
    "CATEGORY_LABELS",
    "CORE_FACT_KEYWORDS",
    "CORE_FACT_METADATA_PREFIX",
    "CORE_FACT_TOLERANCE",
    "COVERAGE_REASON_LABELS",
    "COVERAGE_STATUS_LABELS",
    "CRYPTO",
    "DEFAULT_BUNDLE_BADGE_LABEL",
    "DEFAULT_HISTORY_WINDOW_DAYS",
    "DOMESTIC_EQUITY",
    "FIXED_SECTOR_UNIVERSE",
    "METRIC_QUANTUM",
    "PRIMARY_REGIME_POLICY",
    "RANK_HORIZONS",
    "REGIME_BANDS_BPS",
    "SECTOR_SOURCE_ID",
    "SECTOR_TICKERS",
    "SECTOR_UNIVERSE_VERSION",
    "SEGMENT_LABELS",
    "SEGMENT_MARKET_TZ",
    "SEGMENT_MARKET_TZ_LABEL",
    "SEVERITY_READER_EXPLANATIONS",
    "TELEGRAM_MESSAGE_LIMIT",
    "US_EQUITY",
    "AnchorLabel",
    "AxisState",
    "Briefing",
    "BriefingCarryover",
    "BriefingNotification",
    "CarryoverEventType",
    "CarryoverItem",
    "CarryoverStatus",
    "Category",
    "CoreFact",
    "CoverageReasonCode",
    "CoverageStatus",
    "CoverageStatusInput",
    "CoverageSummary",
    "DiagnosticIssueCode",
    "FactId",
    "FactSnapshot",
    "FactSourceTier",
    "FactStatus",
    "FailureContext",
    "FailureStage",
    "ImpactGroup",
    "MacroLifecycleEvent",
    "MacroLifecycleStatus",
    "MacroMetadataIssue",
    "MacroMetadataIssueCode",
    "MacroMetadataView",
    "MarketAnchor",
    "MarketSegment",
    "MetricMissingReason",
    "MetricValue",
    "NavPoint",
    "NavSeries",
    "NormalizedItem",
    "OHLCRow",
    "ParsedWorkbookSet",
    "PipelineResult",
    "PipelineStatus",
    "PrivateArtifactSet",
    "PrivateDiagnostic",
    "PrivateWorkbookManifest",
    "PublicNotificationSummary",
    "PublicWatchlistGroup",
    "QualityHistoryRow",
    "RankHorizon",
    "RegimePolicy",
    "RegimeResult",
    "RejectReason",
    "RejectedCandidate",
    "RelativeRank",
    "SectorCoverageStatus",
    "SectorDashboardSnapshot",
    "SectorMetricName",
    "SectorMetrics",
    "SectorRecord",
    "SectorRegime",
    "SectorSeriesBundle",
    "SectorTicker",
    "SectorUniverse",
    "SegmentCoverage",
    "SendResult",
    "SourceCollectionReport",
    "SourceOutcome",
    "SourceStatus",
    "SourceTier",
    "TimeState",
    "VerifiedFactBundle",
    "WatchlistChannel",
    "WatchlistImpact",
    "WatchlistImpactCenter",
    "WatchlistImpactStatus",
    "WatchlistMatch",
    "WatchlistTermKind",
    "WorkbookFailure",
    "WorkbookIssueCode",
    "anchor_label",
    "core_fact_metadata_key",
    "is_core_fact",
    "macro_metadata_view",
    "public_watchlist_match_group",
    "public_watchlist_match_label",
    "public_watchlist_match_summary",
    "sanitize_source_error_message",
    "status_label_kr",
]
