"""Deterministic visual asset contracts for briefing cards."""

from investo.visuals.assets import (
    PreparedVisualAssets,
    VisualAssetError,
    insert_visual_links,
    prepare_segment_visual_assets,
    validate_visual_asset,
)
from investo.visuals.cards import (
    CardKind,
    DataConfidenceCardInput,
    MarketSnapshotCardInput,
    PriceSnapshotCardInput,
    PriceSnapshotRow,
    WatchlistRelevanceCardInput,
    WatchlistRelevanceRow,
    build_data_confidence_card,
    build_price_snapshot_card,
    build_watchlist_relevance_card,
)
from investo.visuals.external_image import ExternalImageAsset, fetch_contextual_external_image
from investo.visuals.openai_image import (
    OpenAIVisualConfig,
    generate_openai_visual,
    load_openai_visual_config,
)
from investo.visuals.paths import visual_asset_dir, visual_asset_path, visual_asset_relative_path
from investo.visuals.policy import (
    EXTERNAL_IMAGE_SCRAPING_ENABLED,
    ExternalAssetManifest,
    ExternalAssetPolicyError,
    allowed_external_image_hosts,
    assert_external_asset_allowed,
    assert_external_image_host_allowed,
    external_image_scraping_enabled,
)
from investo.visuals.provenance import (
    GENERATOR_NAME,
    SCHEMA_VERSION,
    VisualProvenanceManifest,
    VisualSourceType,
    build_ai_generated_provenance,
    build_external_provenance,
    build_generated_svg_provenance,
    manifest_path_for,
    provenance_caption,
    read_manifest,
    sanitize_provenance_text,
    write_manifest,
)
from investo.visuals.render import SVG_HEIGHT, SVG_WIDTH, render_card_svg

__all__ = [
    "EXTERNAL_IMAGE_SCRAPING_ENABLED",
    "GENERATOR_NAME",
    "SCHEMA_VERSION",
    "SVG_HEIGHT",
    "SVG_WIDTH",
    "CardKind",
    "DataConfidenceCardInput",
    "ExternalAssetManifest",
    "ExternalAssetPolicyError",
    "ExternalImageAsset",
    "MarketSnapshotCardInput",
    "OpenAIVisualConfig",
    "PreparedVisualAssets",
    "PriceSnapshotCardInput",
    "PriceSnapshotRow",
    "VisualAssetError",
    "VisualProvenanceManifest",
    "VisualSourceType",
    "WatchlistRelevanceCardInput",
    "WatchlistRelevanceRow",
    "allowed_external_image_hosts",
    "assert_external_asset_allowed",
    "assert_external_image_host_allowed",
    "build_ai_generated_provenance",
    "build_data_confidence_card",
    "build_external_provenance",
    "build_generated_svg_provenance",
    "build_price_snapshot_card",
    "build_watchlist_relevance_card",
    "external_image_scraping_enabled",
    "fetch_contextual_external_image",
    "generate_openai_visual",
    "insert_visual_links",
    "load_openai_visual_config",
    "manifest_path_for",
    "prepare_segment_visual_assets",
    "provenance_caption",
    "read_manifest",
    "render_card_svg",
    "sanitize_provenance_text",
    "validate_visual_asset",
    "visual_asset_dir",
    "visual_asset_path",
    "visual_asset_relative_path",
    "write_manifest",
]
